config/routes.rb
Rails.application.routes.draw do
  resources :userdats
  resources :userdata
  root :to => redirect('/upload')
  get '/upload', to: 'welcome#form', constraints: { short_code: /[a-zA-Z]+/ }
  
  post '/upload', to: 'processfile#csv'
  get  '/dbcount', to: 'processfile#dbcount' , constraints: { short_code: /[a-zA-Z]+/ }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/userdat.rb
class Userdat < ApplicationRecord
end

app/models/userdatum.rb
class Userdatum < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/processfile_controller.rb
class ProcessfileController < ApplicationController
  
  
  def csv
  	require("pp")
  	require("csv")
  	require("date")
  	tmp 			= params[:file].tempfile
	destiny_file 	= File.join('public', 'uploads', DateTime.now.to_s+params[:file].original_filename)
	FileUtils.move tmp.path, destiny_file

	input 			=  File.open(destiny_file)
	i				=  0;
	
	bloodgroup		= ["A+", "A-","B+", "B-","O+", "O-","AB+","AB-"]
	success			= "1"
	message			= ""
	tmp				= []
	CSV.foreach(input.path) do |row|
	  inlineSucses	= 1
	  if i > 0	
	  	begin
	  		if(!DateTime.strptime(row[1], '%d.%m.%Y'))
	  			message.concat("DOB not valid at index "+i.to_s+"<br>")
	  			success	= "0"
	  			inlineSucses = 0
	  		end
		rescue ArgumentError
		  	message.concat("DOB not valid at index  "+i.to_s+"<br>")
	  		success	= "0"
	  		inlineSucses = 0
	  	end
	  	
	  	begin
	  		if(!DateTime.strptime(row[2], '%d.%m.%Y %H:%M:%S'))
	  			message.concat("Vaccination timestamp not valid at index  "+i.to_s+"<br>")
	  			success	= "0"
	  			inlineSucses = 0
	  		end
		rescue ArgumentError 
		  	message.concat("Vaccination timestamp not valid at index  "+i.to_s+"<br>")
	  		success	= "0"
	  		inlineSucses = 0
	  	end
	  
	  	if(!bloodgroup.include?(row[4]))
	  		message.concat(",Blood group is not valid at index  "+i.to_s+"<br>")
	  		success	= "0"
	  		inlineSucses = 0
	  	end
	  	
	  	tmp << row
	  	
	  end
	  i 	= i+1
	  
	  
	end
	
	if success == "1"
		for item in tmp 
			udata	= Userdat.new(fullname:item[0],dob:item[1],vaccination:item[2],gender:item[3],bloodgroup:item[4])
			udata.save
		end
		
	end
		
	
	resp			= ["success"=> success,"message"=>message]
	@response		= resp.to_json.html_safe
	
  end
  
  
  
  def dbcount
  
  		udata		= "<table align='center' class='output'>"
  		
  		tmp			= "<tr>"
		tmp			= tmp+"<th>ID</th>"
		tmp			= tmp+"<th>FullName</th>"
		tmp			= tmp+"<th>DOB</th>"
		tmp			= tmp+"<th>Vaccination</th>"
		tmp			= tmp+"<th>Gender</td>"
		tmp			= tmp+"<th>Bloodgroup</th>"
		tmp			= tmp+"<th>Creation Date</th>"
		tmp			= tmp+"</tr>"
		
		udata.concat(tmp);
  		
  		
  		Userdat.find_each(batch_size: 10000).with_index do |user, index|
  			tmp		= "<tr>"
  			tmp		= tmp+"<td>"+user.id.to_s+"</td>"
  			tmp		= tmp+"<td>"+user.fullname.to_s+"</td>"
  			tmp		= tmp+"<td>"+user.dob.to_s+"</td>"
  			tmp		= tmp+"<td>"+user.vaccination.to_s+"</td>"
  			tmp		= tmp+"<td>"+user.gender.to_s+"</td>"
  			tmp		= tmp+"<td>"+user.bloodgroup.to_s+"</td>"
  			tmp		= tmp+"<td>"+user.created_at.to_s+"</td>"
  			tmp		= tmp+"</tr>"
  			
  			udata.concat(tmp)
		end
		udata.concat("</table>")
		
  		@response	= udata.html_safe
  
  end	

end

app/controllers/userdata_controller.rb
class UserdataController < ApplicationController
  before_action :set_userdatum, only: %i[ show edit update destroy ]

  # GET /userdata or /userdata.json
  def index
    @userdata = Userdatum.all
  end

  # GET /userdata/1 or /userdata/1.json
  def show
  end

  # GET /userdata/new
  def new
    @userdatum = Userdatum.new
  end

  # GET /userdata/1/edit
  def edit
  end

  # POST /userdata or /userdata.json
  def create
    @userdatum = Userdatum.new(userdatum_params)

    respond_to do |format|
      if @userdatum.save
        format.html { redirect_to @userdatum, notice: "Userdatum was successfully created." }
        format.json { render :show, status: :created, location: @userdatum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @userdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userdata/1 or /userdata/1.json
  def update
    respond_to do |format|
      if @userdatum.update(userdatum_params)
        format.html { redirect_to @userdatum, notice: "Userdatum was successfully updated." }
        format.json { render :show, status: :ok, location: @userdatum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @userdatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userdata/1 or /userdata/1.json
  def destroy
    @userdatum.destroy
    respond_to do |format|
      format.html { redirect_to userdata_url, notice: "Userdatum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userdatum
      @userdatum = Userdatum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def userdatum_params
      params.require(:userdatum).permit(:fullname, :dob, :vaccination, :gender, :bloodgroup)
    end
end

app/controllers/userdats_controller.rb
class UserdatsController < ApplicationController
  before_action :set_userdat, only: %i[ show edit update destroy ]

  # GET /userdats or /userdats.json
  def index
    @userdats = Userdat.all
  end

  # GET /userdats/1 or /userdats/1.json
  def show
  end

  # GET /userdats/new
  def new
    @userdat = Userdat.new
  end

  # GET /userdats/1/edit
  def edit
  end

  # POST /userdats or /userdats.json
  def create
    @userdat = Userdat.new(userdat_params)

    respond_to do |format|
      if @userdat.save
        format.html { redirect_to @userdat, notice: "Userdat was successfully created." }
        format.json { render :show, status: :created, location: @userdat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @userdat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userdats/1 or /userdats/1.json
  def update
    respond_to do |format|
      if @userdat.update(userdat_params)
        format.html { redirect_to @userdat, notice: "Userdat was successfully updated." }
        format.json { render :show, status: :ok, location: @userdat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @userdat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userdats/1 or /userdats/1.json
  def destroy
    @userdat.destroy
    respond_to do |format|
      format.html { redirect_to userdats_url, notice: "Userdat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userdat
      @userdat = Userdat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def userdat_params
      params.require(:userdat).permit(:fullname, :dob, :vaccination, :gender, :bloodgroup)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  
  def form
  	
  end

  def index
      @wphone = "800.388.2227"
      @wurl = "www.debtadvice.org"
  end

  def privacy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/userdata_helper.rb
module UserdataHelper
end

app/helpers/userdats_helper.rb
module UserdatsHelper
end

app/views/processfile/csv.html.erb
<%= @response %>

app/views/processfile/dbcount.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Udemo Table</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
   	<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "app" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    

  </head>

  <body>
  <h2 class='header2'>
  		Saved Data
  </h2>
  <%= @response %>
  
  </body>
</html>

app/views/userdata/_form.html.erb
<%= form_with(model: userdatum) do |form| %>
  <% if userdatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userdatum.errors.count, "error") %> prohibited this userdatum from being saved:</h2>

      <ul>
        <% userdatum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.text_field :dob %>
  </div>

  <div class="field">
    <%= form.label :vaccination %>
    <%= form.text_field :vaccination %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :bloodgroup %>
    <%= form.text_field :bloodgroup %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/userdata/edit.html.erb
<h1>Editing Userdatum</h1>

<%= render 'form', userdatum: @userdatum %>

<%= link_to 'Show', @userdatum %> |
<%= link_to 'Back', userdata_path %>

app/views/userdata/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userdata</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Dob</th>
      <th>Vaccination</th>
      <th>Gender</th>
      <th>Bloodgroup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userdata.each do |userdatum| %>
      <tr>
        <td><%= userdatum.fullname %></td>
        <td><%= userdatum.dob %></td>
        <td><%= userdatum.vaccination %></td>
        <td><%= userdatum.gender %></td>
        <td><%= userdatum.bloodgroup %></td>
        <td><%= link_to 'Show', userdatum %></td>
        <td><%= link_to 'Edit', edit_userdatum_path(userdatum) %></td>
        <td><%= link_to 'Destroy', userdatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userdatum', new_userdatum_path %>

app/views/userdata/new.html.erb
<h1>New Userdatum</h1>

<%= render 'form', userdatum: @userdatum %>

<%= link_to 'Back', userdata_path %>

app/views/userdata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @userdatum.fullname %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @userdatum.dob %>
</p>

<p>
  <strong>Vaccination:</strong>
  <%= @userdatum.vaccination %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @userdatum.gender %>
</p>

<p>
  <strong>Bloodgroup:</strong>
  <%= @userdatum.bloodgroup %>
</p>

<%= link_to 'Edit', edit_userdatum_path(@userdatum) %> |
<%= link_to 'Back', userdata_path %>

app/views/userdats/_form.html.erb
<%= form_with(model: userdat) do |form| %>
  <% if userdat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userdat.errors.count, "error") %> prohibited this userdat from being saved:</h2>

      <ul>
        <% userdat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :fullname %>
    <%= form.text_field :fullname %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.text_field :dob %>
  </div>

  <div class="field">
    <%= form.label :vaccination %>
    <%= form.text_field :vaccination %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_area :gender %>
  </div>

  <div class="field">
    <%= form.label :bloodgroup %>
    <%= form.text_area :bloodgroup %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/userdats/edit.html.erb
<h1>Editing Userdat</h1>

<%= render 'form', userdat: @userdat %>

<%= link_to 'Show', @userdat %> |
<%= link_to 'Back', userdats_path %>

app/views/userdats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userdats</h1>

<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Dob</th>
      <th>Vaccination</th>
      <th>Gender</th>
      <th>Bloodgroup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userdats.each do |userdat| %>
      <tr>
        <td><%= userdat.fullname %></td>
        <td><%= userdat.dob %></td>
        <td><%= userdat.vaccination %></td>
        <td><%= userdat.gender %></td>
        <td><%= userdat.bloodgroup %></td>
        <td><%= link_to 'Show', userdat %></td>
        <td><%= link_to 'Edit', edit_userdat_path(userdat) %></td>
        <td><%= link_to 'Destroy', userdat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userdat', new_userdat_path %>

app/views/userdats/new.html.erb
<h1>New Userdat</h1>

<%= render 'form', userdat: @userdat %>

<%= link_to 'Back', userdats_path %>

app/views/userdats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @userdat.fullname %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @userdat.dob %>
</p>

<p>
  <strong>Vaccination:</strong>
  <%= @userdat.vaccination %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @userdat.gender %>
</p>

<p>
  <strong>Bloodgroup:</strong>
  <%= @userdat.bloodgroup %>
</p>

<%= link_to 'Edit', edit_userdat_path(@userdat) %> |
<%= link_to 'Back', userdats_path %>

app/views/welcome/form.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Udemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
   	<%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "app" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    

  </head>

  <body>
  
  <h2 class='header'>
  		CSV to Table Insert
  </h2>
  
  <div class="form-style">
	<form>
		<fieldset>
		<legend><span class="number">1</span> Upload the CSV</legend>
		<div id='wrapper'>
			<span class='ftext'>Select File...</span>
			<input type='file' id='browse'>
		</div>
		</fieldset>
		<input type="button" value="Upload" id='upload' />
	</form>
	
	<center>
		<div id='message'>
			
		</div>
	</center>
  </div>
  
  		
  <div class='overlay'></div>
  
  </body>

</html>